Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('accounts/register', views.RegisterFormView.as_view(), name="register"),
    path('accounts/login', views.LoginFormView.as_view(), name="login"),
    path('accounts/settings', views.UserSettingsView.as_view(), name="user_settings"),
    path('accounts/settings_edit', views.UserSettingsViewEdit.as_view(), name="settings_edit"),
    path('accounts/logged_out', views.LogoutFormView.as_view(), name="logout"),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('search.urls',namespace='search')),
    path('', include('comment.urls',namespace='comment'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                       document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserSettings(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth import login as auth_login

from accounts.forms import UserSettings
from blog.mixins import CatApiMixin


class RegisterFormView(CatApiMixin, FormView):
    form_class = UserCreationForm
    success_url = '/'
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(CatApiMixin, LoginView):
    template_name = 'accounts/login.html'

    def get_redirect_url(self):
        return '/'


class LogoutFormView(CatApiMixin, LogoutView):
    next_page = '/'

class UserSettingsView(CatApiMixin, LoginRequiredMixin, TemplateView):
    template_name = 'accounts/settings.html'

class UserSettingsViewEdit(CatApiMixin, LoginRequiredMixin, UpdateView):
    form_class = UserSettings
    success_url = reverse_lazy('accounts:user_settings')
    template_name = 'accounts/settings_edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()
        return super(UserSettingsViewEdit, self).form_valid(form)

templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4 my-5">
            <form method="post">
              {% csrf_token %}
              {{ form|as_bootstrap }}
              <button type="submit" class="save btn btn-dark">Войти</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="row">
        <div class="col-6 my-5">
            <h2>Регистрация</h2>
            <form action="" method="post">
              {% csrf_token %}
              <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
              {{ form|as_bootstrap }}
              <button type="submit" class="save btn btn-dark">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/settings.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6 my-5">
            <div class="card">
                <h3 class="card-header">Личный кабинет пользователя</h3>
                <div class="card-body">
                    <p class="card-text"> <strong>Логин:</strong> {{ request.user.username }} </p>
                    <p class="card-text"> <strong>Имя:</strong> {{ request.user.first_name }}</p>
                    <p class="card-text"> <strong>Фамилия:</strong> {{ request.user.last_name }}</p>
                    <p class="card-text"> <strong>Почта:</strong> {{ request.user.email }}</p>
                    <a type="button" class="btn btn-dark" href={% url 'accounts:settings_edit' %}#posts>Редактировать</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/settings_edit.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="row">
        <div class="col-6 my-5">
            <h3>Редактирование</h3>
            <form method="POST"  class="post-form">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <button type="submit" class="btn btn-secondary">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}