Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('search.urls',namespace='search')),
    path('', include('comment.urls',namespace='comment'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                       document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views


app_name = 'search'

urlpatterns = [
    path('search/search_index', views.SearchView.as_view(), name='search')
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.db.models import Q
from django.views.generic import ListView

from blog.mixins import CatApiMixin
from blog.models import Post


class SearchView(CatApiMixin, ListView):
    model = Post
    template_name = 'search/search_index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
        return object_list

templates/search/search_index.html
{% extends 'base.html' %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
    <div class="row">
        <div class="col my-5">
            {% if object_list %}
                    {% for post in object_list %}
                        <div class="col-12 col-md-4 my-5">
                            <h5 class="card-title"><a href="{% url 'blog:post_detail' pk=post.pk %}#posts">{{ post.title }}</a></h5>
                            <p>{{ post.text|linebreaksbr }}</p>
                            <p class="card-text"><small class="text-muted">Опубликовано: {{ post.published_date }}</small></p>
                        </div>
                    {% endfor %}
            {% else %}
                <p>Ничего не найдено</p>
            {% endif %}
        </div>
    </div>
{% endblock %}