Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns=[
    path('post/<int:pk>/comment', views.NewCommentAddView.as_view(), name='comments'),
    path('post/<int:pk>/comment/edit_comment', views.CommentUpdateView.as_view(), name='commentsupdate'),
    path('post/<int:pk>/comment/delete_comment', views.CommentDeleteView.as_view(), name='commentsdelete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('search.urls',namespace='search')),
    path('', include('comment.urls',namespace='comment'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                       document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    author_post = models.CharField(max_length=200, blank=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    img = models.ImageField(upload_to='media/blog', blank=True, null=True)
    link = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Rss(models.Model):
    title = models.CharField(max_length=200, null=True, verbose_name="Название ссылки")
    url = models.CharField(max_length=100, blank=True, verbose_name="Ссылка для ленты")

    class Meta:
        verbose_name = "Ссылка RSS"
        verbose_name_plural = "Ссылки RSS"

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        labels = {'title':'Заголовок:',
                  'text':'Текст:',
                  'img':'Картинка:',}
        model = Post
        fields = ('title', 'text', 'img', )

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from blog.mixins import CatApiMixin, KanyeApiMixin
from comment.forms import CommentForm
from .models import Post, Rss
from django.utils import timezone
from .forms import PostForm


class PostListView(KanyeApiMixin, ListView):
    model = Post
    queryset = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginate_by = 5


class PostDetailView(KanyeApiMixin, CatApiMixin, DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        form = CommentForm()
        context = super().get_context_data(**kwargs)
        context['form'] = form
        return context


class PostNewView(KanyeApiMixin, LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = "blog/post_edit.html"
    model = Post

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.published_date = timezone.now()
        post.save()
        return super(PostNewView, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_list')


class PostEditView(KanyeApiMixin, LoginRequiredMixin, UpdateView):
    form_class = PostForm
    template_name = 'blog/post_edit.html'
    model = Post

    def form_valid(self, form):
        form.save()
        return super(PostEditView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk':self.object.pk})


class PostDeleteView(KanyeApiMixin, LoginRequiredMixin, DeleteView):
    success_url = "/"
    model = Post
    template_name = 'blog/item_confirm_delete.html'

templates/blog/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-secondary" role="alert">
            Вы действительно хотите удалить запись?
        </div>
        <button class="btn btn-secondary">Удалить</button>
        <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="row">
        <div class="col col-md-8 col-lg-8 mt-5">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title my-3"><strong>{{ post.title }}</strong></h5>
                    {% autoescape off %}<div class="card-text">{{ post.text|linebreaksbr }}</div>{% endautoescape %}
                    {% if post.img %}
                        <img class="card-img-top p-3" src="{{ post.img.url }}">
                    {% endif %}
                    {% if post.published_date %}
                        <p class="card-text">
                            <small class="text-muted">Опубликовано:{{ post.published_date }} Автор: {{ post.author_post }}</small>
                        </p>
                    {% endif %}
                    {% if request.user == post.author %}
                        <a class="btn btn-default float-right" href="{% url 'blog:post_delete' pk=post.pk %}#posts" title="Удалить"><i class="far fa-trash-alt"></i></a>
                        <a class="btn btn-default float-right" href="{% url 'blog:post_edit' pk=post.pk %}#posts" title="Редактировать"><i class="far fa-edit"></i></a>
                    {% endif %}
                </div>
            </div>
            {% for comment in post.comments.all %}
                <div class="card my-5">
                    <div class="card-body">
                        {% if request.user == comment.author_comment %}
                            <a class="btn btn-default float-right" href="{% url 'comment:commentsdelete' pk=comment.pk %}#posts" title="Удалить"><i class="far fa-trash-alt"></i></a>
                            <a class="btn btn-default float-right" href="{% url 'comment:commentsupdate' pk=comment.pk %}#posts" title="Редактировать"><i class="far fa-edit"></i></a>
                        {% endif %}
                        <p class="card-text">{{ comment.comment }}</p>
                        {% if post.published_date %}
                            <p class="card-text"><small class="text-muted">{{ comment.author_comment }} {{ comment.pub_date }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
             <form method="POST" class="my-5" action="{% url "comment:comments" pk=post.pk %}#posts">
                 {% csrf_token %}
                {{ form|as_bootstrap }}
                 <button type="submit" class="save btn btn-dark float-right mb-5">Отправить</button>
             </form>
        </div>
        <div class="col col-md-auto col-lg-4 my-5 float-right">
            <img src="{{ cat }}" alt="..." class="card-image-top" width="400px">
        </div>
    </div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="row">
        <div class="col my-5">
            <h1 class="display-4">Новый пост</h1>
            <form method="POST" class="post-form my-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <button type="submit" class="save btn btn-dark float-right mx-1">Сохранить</button>
                {% if post.pk %}
                    <a href="{% url 'blog:post_detail' pk=post.pk %}#posts" class="btn btn-dark float-right mx-1">Отмена</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% for post in object_list %}
            <div class="col-12 my-5">
                <div class="card mb-3">
                    {% if post.img %}
                        <img class="card-img-top p-3" src="{{ post.img.url }}" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'blog:post_detail' pk=post.pk %}#posts">{{ post.title }}</a></h5>
                        {% if post.link %}<a class="card-text" href="{{ post.link }}">{{ post.link }}</a>{% endif %}
                        {% autoescape off %}<div class="card-text">{{ post.text|linebreaksbr }}</div>{% endautoescape %}
                        <p class="card-text"><small class="text-muted">Опубликовано: {{ post.published_date }} {% if post.author_post %}Автор: {{ post.author_post }}{% endif %}</small></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col float-right">
            {% include "pagination.html" %}
        </div>
    </div>
{% endblock %}