Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('accounts/register', views.RegisterFormView.as_view(), name="register"),
    path('accounts/login', views.LoginFormView.as_view(), name="login"),
    path('accounts/settings', views.UserSettingsView.as_view(), name="user_settings"),
    path('accounts/settings_edit', views.UserSettingsViewEdit.as_view(), name="settings_edit"),
    path('accounts/logged_out', views.LogoutFormView.as_view(), name="logout"),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostNewView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('search.urls',namespace='search')),
    path('', include('comment.urls',namespace='comment'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                       document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views


app_name = 'search'

urlpatterns = [
    path('search/search_index', views.SearchView.as_view(), name='search')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Nastin's blog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://kit.fontawesome.com/52911b89e2.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <section id="intro" style="background-image: url('/media/Оригинал_ 2134x1200.jpeg'); background-size: cover;">
          <div class="container">
            <div class="row align-items-center" style="min-height: 100vh">
              <div class="col-12">
                <h1 class="text-white display-1">Блог</h1>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <blockquote class="blockquote">
                  <p class="mb-0 text-white">"{{ kanye }}"</p>
                  <footer class="blockquote-footer">Kanye West</footer>
                </blockquote>
              </div>
            </div>
          </div>
        </section>
        {% include 'navbar.html' %}
        <section id="posts" style="background-color: #DCDCDC"><a id="razdel"></a>
          <div class="container">
              {% block content %}
              {% endblock %}
          </div>
        </section>
        <section id="footer" class="bg-dark">
          <div class="container">
            <div class="row">
              <div class="col-12 col-md-6 my-5 order-2 order-md-1">
                <ul class="list-unstyled text-white">
                  <li><h6>ABOUT</h6></li>
                  <li class="text-white">We’ve been working on Coding on Steroids
                      for the all our lives.
                      A groundbreaking tech deserves such dedication, huh?
                      If you’d like to learn more, or are interested in a job,
                      contact us anytime at </li>
                </ul>
              </div>
              <div class="col-12 col-md-6 my-5 order-1 order-md-2">
                <ul class="list-unstyled text-white">
                  <li><h6>CONTACTS</h6></li>
                  <li>Tel: 8-800-555-35-35</li>
                  <li>Email: grmgrm@gmail.com</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/"> Главная <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
            {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'blog:post_new' %}#posts">Добавить пост</a>
            {% endif %}
        </li>
    </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search:search' %}" method="get">
        <input name="q" class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Искать</button>
      </form>

    <ul class="navbar-nav ml-auto">
        {% if not request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:login' %}#posts">Вход</a>
        {% endif %}
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{  request.user.username }}</a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{% url 'accounts:user_settings'%}#posts">Личный кабинет</a>
                <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}#posts">Выход</a>
            </div>
          </li>
        {% endif %}
        {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}#posts">Регистрация</a>
            </li>
        {% endif %}
    </ul>
  </div>
</nav>

templates/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-left">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}#posts">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
      {% endif %}
      {% for i in page_obj.paginator.page_range%}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
      {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}#posts">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}#posts">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
      {% endif %}
    </ul>
    </nav>
{% endif %}